mode: svl
velocity: 5
steer_sensitivity: 0.07
debug_window: True
birdeye_warp_param:
  top: 100
  bottom: 180
  top_width: 120
  bottom_width: 180
  birdeye_width: 180
filter_thr_dict:
  saturation_thr: [12,255]
  x_grad_thr: [0,255]
  red_thr: [0,255]
  green_thr: [0,255]
  blue_thr: [100,255]