mode: svl
velocity: 5
steer_sensitivity: 0.03
debug_window: True
birdeye_warp_param:
  top: 80
  bottom: 180
  top_width: 80
  bottom_width: 180
  birdeye_width: 180
filter_thr_dict:
  saturation_thr: [80,170]
  x_grad_thr: [0,100]
  red_thr: [85,255]